- platform: mqtt
  name: "Lampara de pie"
  state_topic: "stat/sonoff02/POWER"
  command_topic: "cmnd/sonoff02/POWER"
  availability_topic: "tele/sonoff02/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "mesa"
  state_topic: "stat/sonoff03/POWER"
  command_topic: "cmnd/sonoff03/POWER"
  availability_topic: "tele/sonoff03/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "lamparita"
  state_topic: "stat/teckin02/POWER"
  command_topic: "cmnd/teckin02/POWER"
  availability_topic: "tele/teckin02/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "shelly25_salon_1"
  state_topic: "shellies/shellyswitch25-007E03/relay/0"
  command_topic: "shellies/shellyswitch25-007E03/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_salon_2"
  state_topic: "shellies/shellyswitch25-007E03/relay/1"
  command_topic: "shellies/shellyswitch25-007E03/relay/1/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_cocina_1"
  state_topic: "shellies/shellyswitch25-007E12/relay/0"
  command_topic: "shellies/shellyswitch25-007E12/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_cocina_2"
  state_topic: "shellies/shellyswitch25-007E12/relay/1"
  command_topic: "shellies/shellyswitch25-007E12/relay/1/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_pasillo_1"
  state_topic: "shellies/shellyswitch25-007E02/relay/0"
  command_topic: "shellies/shellyswitch25-007E02/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_pasillo_2"
  state_topic: "shellies/shellyswitch25-007E02/relay/1"
  command_topic: "shellies/shellyswitch25-007E02/relay/1/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_invitados_1"
  state_topic: "shellies/shellyswitch25-E6645A/relay/0"
  command_topic: "shellies/shellyswitch25-E6645A/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_invitados_2"
  state_topic: "shellies/shellyswitch25-E6645A/relay/1"
  command_topic: "shellies/shellyswitch25-E6645A/relay/1/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_noa_1"
  state_topic: "shellies/shellyswitch25-BCDDC27756D3/relay/0"
  command_topic: "shellies/shellyswitch25-BCDDC27756D3/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "shelly25_noa_2"
  state_topic: "shellies/shellyswitch25-BCDDC27756D3/relay/1"
  command_topic: "shellies/shellyswitch25-BCDDC27756D3/relay/1/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  schema: template
  name:  "Luz dormitorio"
  state_topic: "shellies/shellydimmer-D464E0/light/0/status"
  state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
  command_topic: "shellies/shellydimmer-D464E0/light/0/set"
  command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
  command_off_template: '{"turn": "off"}'
  brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'
- platform: mqtt
  name: "Armario dormitorio"
  state_topic: "shellies/shelly1-F4CFA2767E29/relay/0"
  command_topic: "shellies/shelly1-F4CFA2767E29/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "Terraza Grande"
  state_topic: "shellies/shelly1-F4CFA274892B/relay/0"
  command_topic: "shellies/shelly1-F4CFA274892B/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "Terraza Pequena"
  state_topic: "shellies/shelly1-F4CFA27488BF/relay/0"
  command_topic: "shellies/shelly1-F4CFA27488BF/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: "Shelly10_test"
  state_topic: "shellies/shelly1-500291F0636D/relay/0"
  command_topic: "shellies/shelly1-500291F0636D/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: switch
  name: Cabezon
  entity_id: switch.cabezon